#!/bin/bash
## Description: [DevTool] Rebuild the local environment by destroying all data.
## Usage: rebuild

ddev rm -RO
rm web/sites/default/civicrm.settings.php
rm -rf private/civicrm
ddev start
ddev exec drush si --account-pass=admin --yes -vvv
ddev uli
